name: Deploy Frontend to FreeInfinity

on:
  push:
    branches:
      - main # Change this to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: bmscestudentcompanion/CompanionSite
        ref: main
        path: CompanionSite # Specify the path to checkout the repository
    
    - name: Deploy to FreeInfinity
      run: |
        # Change to the 'BMSCE_Companion' directory
        cd ./CompanionSite/BMSCE_Companion
        # Loop through each frontend file and upload it using curl
        for file in *; do
          # Modify the target directory to match your server structure
          curl --ftp-pasv -T "$file" -u $if0_34806115:$NmjOePTLzNR https://filemanager.ai/new/#/c/185.27.134.11/if0_34806115/eyJ0IjoiZnRwIiwiYyI6eyJwIjoiTm1qT2VQVEx6TlIiLCJpIjoiaHRkb2NzIn19
        done
