name: Deploy Frontend Images to FreeInfinity

on:
  push:
    branches:
      - main # Change this to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Deploy to FreeInfinity
      run: |
        # Change to the 'image' directory
        cd ./BMSCE_Companion/BMSCE_Companion
        # Loop through each image file and upload it using curl
        for file in *; do
          curl -T "$file" -u $if0_34806115:$NmjOePTLzNR ftp://ftpupload.net/public_html/
        done
